#!/usr/bin/env python3
"""Rebuild the curated browser catalog from the committed OpenNGC seed (no network)."""
import csv, json, pathlib, re
ROOT = pathlib.Path(__file__).resolve().parents[1]

def sexagesimal(value):
    sign = -1 if value.startswith('-') else 1
    parts = [float(x) for x in value.lstrip('+-').split(':')]
    return sign * (parts[0] + parts[1]/60 + parts[2]/3600)

def optional(value):
    return float(value) if value else None

notes = json.loads((ROOT/'data/target-notes.json').read_text())
targets = []
for row in csv.DictReader((ROOT/'data/openngc-seed.csv').open(), delimiter=';'):
    note = notes[row['Name']]
    catalog_id = re.sub(r'^(NGC|IC)0*', r'\1 ', row['Name'])
    designation = 'M'+str(int(row['M'])) if row['M'] else catalog_id
    targets.append(dict(id=row['Name'].lower(), designation=designation, catalogId=row['Name'],
        name=note.get('name') or row['Common names'].split(',')[0] or designation,
        aliases=[catalog_id]+[name for name in row['Common names'].split(',') if name], objectType=note['type'],
        catalogType=row['Type'], constellation=row['Const'], epoch='J2000',
        raHours=sexagesimal(row['RA']), decDeg=sexagesimal(row['Dec']),
        majorArcmin=optional(row['MajAx']), minorArcmin=optional(row['MinAx']),
        positionAngleDeg=optional(row['PosAng']), magnitudeV=optional(row['V-Mag']),
        surfaceBrightness=optional(row['SurfBr']), sources=row['Sources'],
        lightPollution=note['lightPollution'], framingReliable=note.get('framingReliable',True),
        notes=note.get('notes','')))
assert len(targets)==len(notes) and len({t['id'] for t in targets})==len(targets)
for t in targets:
    assert 0<=t['raHours']<24 and -90<=t['decDeg']<=90
catalog=dict(version='2026.09.19',license='CC-BY-SA-4.0',attribution='OpenNGC — Mattia Verga and contributors',
    source='https://github.com/mattiaverga/OpenNGC',sourceCommit='36cb178a0f69dba8bfc03a99c10512831edf1c6b',targets=targets)
(ROOT/'data/targets.js').write_text('// Generated by scripts/build-catalog.py. Data: CC-BY-SA-4.0; see data/README.md.\nconst AstroCatalog='+json.dumps(catalog,ensure_ascii=False,indent=2)+';\nif(typeof module!=="undefined")module.exports=AstroCatalog;\n')
print(f'Built {len(targets)} targets')
